language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - sudo apt-get install gcc gcc-c++ kernel-devel
  - sudo apt-get install libsnappy1 # Install google snappy
  - pip install --editable . # Install it self
  - pip install -r requirements-test.txt # Install test dependencies
  - pip install codecov # Install coveralls

script:
  - pytest tests --cov=compress # Run unittest

notifications:
  email: false # Mute email notification

after_success:
  - codecov # travis-ci will transfer data to codecov after success